create table if not exists User
(
    user_id         integer generated by default as identity ,
    nickname        varchar(25),
    password        varchar(256),
    created_on      datetime,
    modified_on     datetime,
    email           varchar(40),
    primary key (user_id)
);
