create table if not exists User
(
    user_id         integer generated by default as identity,
    nickname        varchar(25),
    password        varchar(256),
    created_on      datetime,
    modified_on     datetime,
    email           varchar(40),
    primary key (user_id)
);

create table if not exists Body_Part
(
    body_part_id         integer generated by default as identity,
    body_part_name       varchar(45),
    primary key (body_part_id)
);

create table if not exists Exercise_Type
(
    type_id         integer generated by default as identity,
    type_name       varchar(45),
    primary key (type_id)
);

create table if not exists Exercise
(
    exercise_id         integer generated by default as identity,
    name                varchar(45),
    exercise_type_id    integer,
    body_part_id        integer,
    primary key (exercise_id),
    foreign key (exercise_type_id) references Exercise_Type (type_id),
    foreign key (body_part_id) references Body_Part (body_part_id)
);

create table if not exists Exercise_Routine
(
    routine_id      integer generated by default as identity,
    user_id         integer,
    day_of_week     integer,
    primary key (routine_id),
    foreign key (user_id) references User (user_id)
)
